config/routes.rb
FlatRent::Application.routes.draw do
  resources :chats

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  
  resources :offer_photos
  resources :auctions

  resources :photos

  resources :shouts


  resources :offers

  get 'users/ranking'
  resources :events do
    collection do
         get :likeit
     end
  end

#  authenticated do
    root :to => 'home#create', as: :authenticated
#  end
#  devise_scope :user do
#    root to: "devise/sessions#new"
#  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/models/offer_photo.rb
class OfferPhoto < ActiveRecord::Base
	mount_uploader :photo, PictureUploader
	belongs_to :offer
end

app/controllers/offer_photos_controller.rb
class OfferPhotosController < ApplicationController
  before_action :set_offer_photo, only: [:show, :edit, :update, :destroy]

  # GET /offer_photos
  # GET /offer_photos.json
  def index
    @offer_photos = OfferPhoto.all
  end

  # GET /offer_photos/1
  # GET /offer_photos/1.json
  def show
  end

  # GET /offer_photos/new
  def new
    @offer_photo = OfferPhoto.new
  end

  # GET /offer_photos/1/edit
  def edit
  end

  # POST /offer_photos
  # POST /offer_photos.json
  def create
    @offer_photo = OfferPhoto.new(offer_photo_params)

    respond_to do |format|
      if @offer_photo.save
        format.html { redirect_to @offer_photo, notice: 'Offer photo was successfully created.' }
        format.json { render :show, status: :created, location: @offer_photo }
      else
        format.html { render :new }
        format.json { render json: @offer_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offer_photos/1
  # PATCH/PUT /offer_photos/1.json
  def update
    respond_to do |format|
      if @offer_photo.update(offer_photo_params)
        format.html { redirect_to @offer_photo, notice: 'Offer photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer_photo }
      else
        format.html { render :edit }
        format.json { render json: @offer_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offer_photos/1
  # DELETE /offer_photos/1.json
  def destroy
    @offer_photo.destroy
    respond_to do |format|
      format.html { redirect_to offer_photos_url, notice: 'Offer photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer_photo
      @offer_photo = OfferPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_photo_params
      params.require(:offer_photo).permit(:offer_id, :photo)
    end
end

app/helpers/offer_photos_helper.rb
module OfferPhotosHelper
end

app/views/offer_photos/_form.html.erb
<%= simple_form_for(@offer_photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :offer_id %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/offer_photos/edit.html.erb
<h1>Editing offer_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer_photo %> |
<%= link_to 'Back', offer_photos_path %>

app/views/offer_photos/index.html.erb
<h1>Listing offer_photos</h1>

<table>
  <thead>
    <tr>
      <th>Offer</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offer_photos.each do |offer_photo| %>
      <tr>
        <td><%= offer_photo.offer_id %></td>
        <td><%= offer_photo.photo %></td>
        <td><%= link_to 'Show', offer_photo %></td>
        <td><%= link_to 'Edit', edit_offer_photo_path(offer_photo) %></td>
        <td><%= link_to 'Destroy', offer_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer photo', new_offer_photo_path %>

app/views/offer_photos/new.html.erb
<h1>New offer_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', offer_photos_path %>

app/views/offer_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Offer:</strong>
  <%= @offer_photo.offer_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @offer_photo.photo %>
</p>

<%= link_to 'Edit', edit_offer_photo_path(@offer_photo) %> |
<%= link_to 'Back', offer_photos_path %>