config/routes.rb
FlatRent::Application.routes.draw do
  resources :chats

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  
  resources :offer_photos
  resources :auctions

  resources :photos

  resources :shouts


  resources :offers

  get 'users/ranking'
  resources :events do
    collection do
         get :likeit
     end
  end

#  authenticated do
    root :to => 'home#create', as: :authenticated
#  end
#  devise_scope :user do
#    root to: "devise/sessions#new"
#  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/chats_controller.rb
class ChatsController < InheritedResources::Base
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= simple_form_for(@chat) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<h4><b>Shoutbox</b></h4>
<% shoutbox = String.new("") %>
<ul>
<% for shout in @shouts %>
<% shoutbox = shoutbox + "Author: #{shout.name} \n #{shout.message} \n___________________________________________________________________________________________\n" %>
<% end %>
      <%= text_area_tag(:shoutboxing, "#{shoutbox}", rows: '10', cols: 80, readonly: "true", style: "resize:none;color:brown;background-color:#C0C0C0") %><br>
</ul>
<%= form_for @shout do |f| %>

<% f.label :name %><b>Name:</b>
<%= f.text_field :name, :size => 20 %><br>

<% f.label :message %><b>Message:</b><br>
<%= f.text_area :message, :rows => 3, :cols => 80, style: "resize:none" %><br>

<%= f.submit %>
<% end %>

app/views/chats/new.html.erb
<%= form_for @shout do |form| %>

	<%= form.label :name %>
	<%= form.text_field :name %>

	<%= form.label :message %>
	<%= form.text_area :message %>
	
	<%= form.submit %>

<% end %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>