config/routes.rb
FlatRent::Application.routes.draw do
  resources :chats

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  
  resources :offer_photos
  resources :auctions

  resources :photos

  resources :shouts


  resources :offers

  get 'users/ranking'
  resources :events do
    collection do
         get :likeit
     end
  end

#  authenticated do
    root :to => 'home#create', as: :authenticated
#  end
#  devise_scope :user do
#    root to: "devise/sessions#new"
#  end
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	 belongs_to :user, counter_cache: true
	 has_many :auctions

	 searchable do
    	text :title, :description, :localization
  	 end

	 has_many :offer_photos
	 accepts_nested_attributes_for :offer_photos
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @search = Offer.search do
      fulltext params[:search]
    end
  @offers  = @search.results
  end

  def sort_column
    Offer.column_names.include?(params[:sort]) ? params[:sort] : "Rooms"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


  # GET /offers/1
  # GET /offers/1.json
  def show
    @photos = @offer.offer_photos.all
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @photo = @offer.offer_photos.build
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id 

    respond_to do |format|
      if @offer.save
        if params[:offer_photos]
          params[:offer_photos]['photo'].each do |a|
            @photo = @offer.offer_photos.create!(:photo => a, :offer_id => @offer.id)
          end
        end
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        if params[:offer_photos]
          params[:offer_photos]['photo'].each do |a|
            @photo = @offer.offer_photos.create!(:photo => a, :offer_id => @offer.id)
          end
        end
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :cost, :picture, :start_date, :end_date, :area, :rooms, :localization, :description, offer_photos_attributes: [:id, :offer_id, :photo])
    end
end

app/helpers/offers_helper.rb
module OffersHelper
	def sortable(column, title = nil)
  	title ||= column.titleize
  	css_class = column == sort_column ? "current #{sort_direction}" : nil
  	direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  	link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/views/offers/_form.html.erb
<div class="authform">
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.label :title %>
     <%= f.text_field :title, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :cost %>
    <%= f.text_field :cost, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :start_date, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :end_date, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :area %>
     <%= f.text_field :area, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :rooms, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :localization %>
     <%= f.text_field :localization, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.input :description, :autofocus => true, class: 'form-control' %>
    <%= f.hidden_field :user_id %> 
  </div>

  <%= f.fields_for :offer_photo do |p| %>
     <div class="field">
       <%= p.label :photo %><br>
       <%= p.file_field :photo, :multiple => true, name: "offer_photos[photo][]" %>
     </div>
   <% end %>

   <% if params[:action] == "edit" %> 
     <% @offer.offer_photos.each do |p| %>
       <%= image_tag p.photo, :size => "150x150" %>
       <%= link_to "Destroy", p, method: :delete %>
     <% end %>
   <% end %>

  <div class="form-actions">
    <%= f.submit 'Submit', :class => 'button right' %>
  </div>
<% end %>
</div>

app/views/offers/edit.html.erb
<div class='head'>
<h1>Editing offer</h1>
</div>

<%= render 'form' %>

<%= link_to "<button>Show</button>".html_safe, @offer, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
<%= link_to "<button>Back</button>".html_safe, offers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>

app/views/offers/index.html.erb
<div style="float:right;">
  <%= form_tag offers_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
<% end %></div>
<h1>Listing offers</h1>

<style>
    td, th {
        padding: 10px;
    }
</style>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th><%= sortable "cost","cost" %></th>
      <th>Picture</th>
      <th><%= sortable "start_date" %></th>
      <th><%= sortable "end_date" %></th>
      <th>Area</th>
      <th><%= sortable "Rooms" %></th>
      <th><%= sortable "localization" %></th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td class="price"><%= number_to_currency(offer.cost) %></td>
        <td><%= offer.picture %></td>
        <td><%= offer.start_date %></td>
        <td><%= offer.end_date %></td>
        <td><%= offer.area %></td>
        <td><%= offer.rooms %></td>
        <td><%= offer.localization %></td>
        <td><%= offer.description %></td>
        <td><%= link_to "<button>Show</button>".html_safe, offer, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %></td>
        <td><%= link_to "<button>Edit</button>".html_safe, (edit_offer_path(offer) if offer.user_id == current_user.id), :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %></td>
        <td><%= link_to "<button>Destroy</button>".html_safe, offer, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip",method: :delete, data: { confirm: 'Are you sure?' } if offer.user_id == current_user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/offers/new.html.erb
<div class='head'>
<h1>New offer</h1>
</div>
<%= render 'form' %>

<%= link_to "<button>Back</button>".html_safe, offers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>

app/views/offers/show.html.erb
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Geocoding service</title>
    <style>
       #map-canvas {
        height: 250px;
        width: 300px;
        margin: 0px;
        padding: 0px
      }
      #panel {
        position: absolute;
        top: 5px;
        left: 700%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
</head>
<p id="notice"><%= notice %></p>

<div class='event_view'>

<div class='head'>
  <strong><%= @offer.title %></strong>
</div>
<div id='txt'>
<p>
  <strong>Cost:</strong>
  <%= @offer.cost %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @offer.picture %>
</p>

<%= image_tag('/images/icotime.png') %>
<p id='picture'>
  <strong>Start date:</strong>
  <%= @offer.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @offer.end_date %>
</p>

<p>
  <strong>Area:</strong>
  <%= @offer.area %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @offer.rooms %>
</p>

<%= image_tag('/images/icoplace.png') %>
<p id='picture'>
  <strong>Localization:</strong>
  <%= @offer.localization %>
</p>
</div>
<div id='descript'> 
<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<% @photos.each do |p| %>
  <%= image_tag p.photo_url %>
  <br />
<% end %>
</div>
<%= link_to "<button>Edit</button>".html_safe,  edit_offer_path(@offer), :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
   <%= link_to "<button>Back</button>".html_safe,  offers_path, :id=>"open-contacts-dialog-btn", :class=>"inbox-sf-add-btn tip" %>
</div>

<h2>Bids:</h2>
 
<h4>The highest offer: <%= Auction.where(offer_id: @offer.id).order(bid: :desc).first.user.name if !@offer.auctions.empty?%></h4>
 <tbody>

<% Auction.where(offer_id: @offer.id).order(bid: :desc).each do |auction| %>
    <tr>  
        <td><%= auction.bid %></td>
        <td><%= auction.user.name %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } if auction.user == current_user%></td>
      </tr>
      <br>
    <% end %>
</tbody>
<%= render 'auctions/form' %>

<%= link_to 'Back', auctions_path %>
<p id="pdf_link"><%= link_to "Download (PDF)", offer_path(@offer, :format => "pdf") %></p>




<script>
  var geocoder;
  var map;
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var mapOptions = {
      zoom: 15,
      center: latlng
    }
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var address = '<%= @offer.localization  %>';
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
    }
  google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="map-canvas"></div>